[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  NPM_FLAGS = "--production=false"

# Functions configuration
[functions]
  directory = "netlify/functions"

# API redirects - these must come before the SPA redirect
[[redirects]]
  from = "/api/areas/search"
  to = "/.netlify/functions/areas-search"
  status = 200

[[redirects]]
  from = "/api/areas/all"
  to = "/.netlify/functions/areas-all"
  status = 200

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200

[[redirects]]
  from = "/api/categories/search"
  to = "/.netlify/functions/api?path=/api/categories/search"
  status = 200

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/api?path=/api/auth/signup"
  status = 200

[[redirects]]
  from = "/api/auth/freelancer-signup"
  to = "/.netlify/functions/api?path=/api/auth/freelancer-signup"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/api?path=/api/users"
  status = 200

[[redirects]]
  from = "/api/leads"
  to = "/.netlify/functions/api?path=/api/leads"
  status = 200

[[redirects]]
  from = "/api/freelancers"
  to = "/.netlify/functions/api?path=/api/freelancers"
  status = 200

[[redirects]]
  from = "/api/test-db"
  to = "/.netlify/functions/api?path=/api/test-db"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/api?path=/api/test"
  status = 200


# Redirect rules for SPA - this is critical
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Headers for better performance and security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
