[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "false"
  NPM_FLAGS = "--production=false"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API redirects - Route all API calls to the simple handler (temporary)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple?path=:splat"
  status = 200

# Specific API redirects for better routing
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/api-simple?path=/api/test"
  status = 200

[[redirects]]
  from = "/api/test-db"
  to = "/.netlify/functions/api-simple?path=/api/test-db"
  status = 200

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/api-simple?path=/api/auth/signup"
  status = 200

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/api-simple?path=/api/categories"
  status = 200

[[redirects]]
  from = "/api/areas"
  to = "/.netlify/functions/api-simple?path=/api/areas"
  status = 200

[[redirects]]
  from = "/api/freelancers"
  to = "/.netlify/functions/api-simple?path=/api/freelancers"
  status = 200

[[redirects]]
  from = "/api/customer/profile"
  to = "/.netlify/functions/api-simple?path=/api/customer/profile"
  status = 200

[[redirects]]
  from = "/api/test-simple"
  to = "/.netlify/functions/test-simple"
  status = 200


# Redirect rules for SPA - this is critical
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Headers for better performance and security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
