CREATE TABLE "areas" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	"city" varchar NOT NULL DEFAULT 'Jaipur',
	"state" varchar NOT NULL DEFAULT 'Rajasthan',
	"country" varchar NOT NULL DEFAULT 'India',
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"is_active" boolean DEFAULT true,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "areas_name_unique" UNIQUE("name")
);
INSERT INTO "areas" ("name", "city", "state", "country") VALUES
('Adarsh Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Agra Road', 'Jaipur', 'Rajasthan', 'India'),
('Ajmer Road', 'Jaipur', 'Rajasthan', 'India'),
('Ajmeri Gate', 'Jaipur', 'Rajasthan', 'India'),
('Ambabari', 'Jaipur', 'Rajasthan', 'India'),
('Amer', 'Jaipur', 'Rajasthan', 'India'),
('Amer Road', 'Jaipur', 'Rajasthan', 'India'),
('Bais Godam', 'Jaipur', 'Rajasthan', 'India'),
('Bajaj Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Bani Park', 'Jaipur', 'Rajasthan', 'India'),
('Bapu Bazaar', 'Jaipur', 'Rajasthan', 'India'),
('Bapu Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Barkat Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Bhawani Singh Road', 'Jaipur', 'Rajasthan', 'India'),
('Biseswarji', 'Jaipur', 'Rajasthan', 'India'),
('Bindayaka', 'Jaipur', 'Rajasthan', 'India'),
('Brahmapuri', 'Jaipur', 'Rajasthan', 'India'),
('Bagru', 'Jaipur', 'Rajasthan', 'India'),
('Chandpol', 'Jaipur', 'Rajasthan', 'India'),
('Chhoti Chaupar', 'Jaipur', 'Rajasthan', 'India'),
('Civil Lines', 'Jaipur', 'Rajasthan', 'India'),
('C-Scheme', 'Jaipur', 'Rajasthan', 'India'),
('Durgapura', 'Jaipur', 'Rajasthan', 'India'),
('Dholai', 'Jaipur', 'Rajasthan', 'India'),
('Gangori Bazaar', 'Jaipur', 'Rajasthan', 'India'),
('Ghat Darwaza', 'Jaipur', 'Rajasthan', 'India'),
('Goner', 'Jaipur', 'Rajasthan', 'India'),
('Gopalpura', 'Jaipur', 'Rajasthan', 'India'),
('Gopalpura Bypass', 'Jaipur', 'Rajasthan', 'India'),
('Govindpura', 'Jaipur', 'Rajasthan', 'India'),
('Hathroi', 'Jaipur', 'Rajasthan', 'India'),
('Indira Bazar', 'Jaipur', 'Rajasthan', 'India'),
('Jagatpura', 'Jaipur', 'Rajasthan', 'India'),
('Jalupura', 'Jaipur', 'Rajasthan', 'India'),
('Janata Colony', 'Jaipur', 'Rajasthan', 'India'),
('Jawaharlal Nehru Marg', 'Jaipur', 'Rajasthan', 'India'),
('Jawahar Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Jhotwara', 'Jaipur', 'Rajasthan', 'India'),
('Jhotwara Industrial Area', 'Jaipur', 'Rajasthan', 'India'),
('Jhotwara Road', 'Jaipur', 'Rajasthan', 'India'),
('Johari Bazar', 'Jaipur', 'Rajasthan', 'India'),
('Jyothi Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Kanakapura', 'Jaipur', 'Rajasthan', 'India'),
('Kanota', 'Jaipur', 'Rajasthan', 'India'),
('Kalwar Road', 'Jaipur', 'Rajasthan', 'India'),
('Kartarpura', 'Jaipur', 'Rajasthan', 'India'),
('Khatipura', 'Jaipur', 'Rajasthan', 'India'),
('Mahesh Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Malviya Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Mansarovar', 'Jaipur', 'Rajasthan', 'India'),
('Mansarovar Extension', 'Jaipur', 'Rajasthan', 'India'),
('Mirza Ismail Road', 'Jaipur', 'Rajasthan', 'India'),
('MI Road', 'Jaipur', 'Rajasthan', 'India'),
('Moti Doongri', 'Jaipur', 'Rajasthan', 'India'),
('Muralipura', 'Jaipur', 'Rajasthan', 'India'),
('Nirman Nagar', 'Jaipur', 'Rajasthan', 'India'),
('New Colony', 'Jaipur', 'Rajasthan', 'India'),
('New Sanganer Road', 'Jaipur', 'Rajasthan', 'India'),
('Patrakar Colony', 'Jaipur', 'Rajasthan', 'India'),
('Pink City', 'Jaipur', 'Rajasthan', 'India'),
('Pratap Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Raja Park', 'Jaipur', 'Rajasthan', 'India'),
('Ramnagar', 'Jaipur', 'Rajasthan', 'India'),
('Sanganer', 'Jaipur', 'Rajasthan', 'India'),
('Sansar Chandra Road', 'Jaipur', 'Rajasthan', 'India'),
('Sethi Colony', 'Jaipur', 'Rajasthan', 'India'),
('Shastri Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Shyam Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Sirsi Road', 'Jaipur', 'Rajasthan', 'India'),
('Sikar Road', 'Jaipur', 'Rajasthan', 'India'),
('Sitapura', 'Jaipur', 'Rajasthan', 'India'),
('Sitapura Industrial Area', 'Jaipur', 'Rajasthan', 'India'),
('Sodala', 'Jaipur', 'Rajasthan', 'India'),
('Subhash Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Sudharshanpura Industrial Area', 'Jaipur', 'Rajasthan', 'India'),
('Surajpol Bazar', 'Jaipur', 'Rajasthan', 'India'),
('Tilak Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Tonk Phatak', 'Jaipur', 'Rajasthan', 'India'),
('Tonk Road', 'Jaipur', 'Rajasthan', 'India'),
('Transport Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Tripolia Bazaar', 'Jaipur', 'Rajasthan', 'India'),
('Vaishali Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Vidhyadhar Nagar', 'Jaipur', 'Rajasthan', 'India'),
('Vishwakarma Industrial Area', 'Jaipur', 'Rajasthan', 'India'),
('Bassi', 'Jaipur', 'Rajasthan', 'India'),
('Chaksu', 'Jaipur', 'Rajasthan', 'India'),
('Chomu', 'Jaipur', 'Rajasthan', 'India'),
('Jamdoli', 'Jaipur', 'Rajasthan', 'India'),
('Jamwa Ramgarh', 'Jaipur', 'Rajasthan', 'India'),
('Kukas', 'Jaipur', 'Rajasthan', 'India'),
('Samode', 'Jaipur', 'Rajasthan', 'India'),
('Chandlai', 'Jaipur', 'Rajasthan', 'India');
